spring:
    application:
        name: springboot-spark-pipeline

    #   MySQL Database Configuration
    datasource:
        url: jdbc:mysql://localhost:3306/product_revenue_db
        username: root
        password: 2002
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true